---
- name: Create folder
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - /var/delay-prediction

- name: Install script file
  template:
    src: "{{ item }}"
    dest: /var/delay-prediction/
    mode: "+x"
  with_items:
    - build
    - start
    - stop
    - cleanup

- name: Install base packages
  package:
    name:
      - python-docker
    state: present

- name: Create photon network
  docker_network:
    name: delay

- name: Install systemd files
  template:
    src: '{{ item }}'
    dest: /etc/systemd/system/
  with_items:
    - delay-postgis.service
    - delay-prediction.service
  notify: Restart delay-prediction-service

- name: Start service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - delay-postgis.service
    - delay-prediction.service
  when: enable_prediction_service

- name: Stop service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: yes
    daemon_reload: yes
  with_items:
    - delay-postgis.service
    - delay-prediction.service
  when: enable_prediction_service == false
