version: '3'

services:
  opentripplanner:
    image: {{ digitransit["images"]["otp"] }}
    restart: on-failure:5
    container_name: opentripplanner
    logging:
      driver: journald
    ports:
      - {{otp_port}}:8080
    command: --load --serve graph
    environment:
      - ROUTER_NAME=hb
      - API_URL=https://{{ api_hostname }}/otp/routers/default/
      - ENCRYPTION_SECRET_KEY={{ encryption_secret_key }}
      - JAVA_OPTS=-Xmx12G
    volumes:
      - /var/graph-build/latest/:/opt/opentripplanner/graph/

{% for item in digitransit_ui %}
  digitransit-ui-{{ item["config"] }}:
    image: {{ item["image"] }}
    restart: on-failure
    container_name: digitransit-ui-{{ item["config"]}}
    ports:
      - {{ item["port"] }}:8080
    networks:
      - digitransit
    logging:
      driver: journald
    environment:
      - CONFIG={{ item["config"] }}
      - GEOCODING_BASE_URL={{ photon_url }}/pelias/v1
      - API_URL=https://{{ api_hostname }}
      - MAP_URL={{ map_url }}
      - SEMI_TRANSPARENT_MAP_URL={{ semi_transparent_map_url }}
      - NODE_ENV=production
      - FAHRGEMEINSCHAFT_API_KEY={{ fahrgemeinschaft_api_key }}
      - FAHRGEMEINSCHAFT_AUTH_KEY={{ fahrgemeinschaft_auth_key }}
{% endfor %}

  hsl-map-server:
    image: {{ digitransit["images"]["map_server"] }}
    container_name: hsl-map-server
    restart: on-failure:5
    networks:
      - digitransit
    ports:
      - {{ map_server_port }}:8080
    environment:
      - PARK_API_URL=https://{{ api_hostname }}/herrenberg/parking/parkapi.json
      - GRAPHQL_URL=https://api.stadtnavi.de/routing/v1/router/index/graphql
      - OTP_URL=https://api.stadtnavi.de/routing/v1/router/index/graphql
      - CIFS_URL=https://data.mfdz.de/hbg/roadworks/cifs.json
      - WEATHER_STATIONS_URL=https://{{ api_hostname }}/herrenberg/weather/weather.geojson
      - CHARGING_STATIONS_URL=https://{{ api_hostname }}/herrenberg/charging-stations/charging-stations.geojson
    logging:
      driver: journald

  graphiql:
    image: corykitchens/graphiql:latest
    container_name: graphiql
    restart: on-failure:5
    networks:
      - digitransit
    ports:
      - {{ graphiql_port }}:4000
    environment:
      - API_URL=https://api.dev.stadtnavi.eu/routing/v1/router/index/graphql
    logging:
      driver: journald

  fares-service:
    image: {{ digitransit["images"]["fares_service"] }}
    container_name: fares-service
    restart: on-failure:5
    networks:
      - digitransit
    ports:
      - {{ fares_service_port }}:3000
    environment:
      - TRIAS_REQUESTOR_REF={{ trias_api_key }}
    logging:
      driver: journald

networks:
  digitransit:
    # all default
